# Changes here will be overwritten by Copier
_commit: v3.1.1
_src_path: gh:eccenca/cmem-plugin-template
author_mail: cmempy-developer@eccenca.com
author_name: eccenca
project_description: Send messages to Apache Kafka.
project_slug: kafka

