# Changes here will be overwritten by Copier
_commit: v3.3.2
_src_path: gh:eccenca/cmem-plugin-template
author_mail: cmempy-developer@eccenca.com
author_name: eccenca GmbH
project_description: Send and receive messages from Apache Kafka.
project_slug: kafka

