# Changes here will be overwritten by Copier
_commit: v7.3.0-21-gd03545f
_src_path: gh:eccenca/cmem-plugin-template
author_mail: cmempy-developer@eccenca.com
author_name: eccenca GmbH
github_page: https://github.com/eccenca/cmem-plugin-kafka
project_description: Send and receive messages from Apache Kafka.
project_slug: kafka
project_type: plugin
pypi: true

