# Changes here will be overwritten by Copier
_commit: v5.2.0
_src_path: gh:eccenca/cmem-plugin-template
author_mail: cmempy-developer@eccenca.com
author_name: eccenca GmbH
github_page: https://github.com/eccenca/cmem-plugin-kafka
project_description: Send and receive messages from Apache Kafka.
project_slug: kafka
pypi: true

