---
default:
  image: docker-registry.eccenca.com/eccenca-python:feature_3.9 
  services:
    - name: blacktop/kafka
      alias: kafka

variables:
  KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,INTERNAL://localhost:9093'
  KAFKA_BROKER_ID: '1'
  KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
  KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:9093'
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT'
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  KAFKA_CREATE_TOPICS: "eccenca_kafka:1:1"
    
stages:
  - test
  - build

check:
  stage: test
  script:
    - task check
  artifacts:
    when: always
    reports:
      cobertura:
        - ./dist/coverage.xml
      junit:
        - ./dist/junit-bandit.xml
        - ./dist/junit-flake8.xml
        - ./dist/junit-mypy.xml
        - ./dist/junit-pylint.xml
        - ./dist/junit-pytest.xml
    paths:
      - ./dist/badge-coverage.svg
      - ./dist/badge-tests.svg
      - ./dist/coverage
      - ./dist/coverage.xml

build:
  stage: build
  script:
    - task build
  artifacts:
    when: always
    paths:
      - ./dist/*.tar.gz
      - ./dist/*.whl
